// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Hyper/config"
	"Hyper/dao"
	"Hyper/handler"
	"Hyper/pkg/client"
	"Hyper/pkg/database"
	"Hyper/pkg/server"
	"Hyper/service"
)

// Injectors from wire.go:

func InitServer(cfg *config.Config) *server.AppProvider {
	db := database.NewDB(cfg)
	users := dao.NewUsers(db)
	redisClient := client.NewRedisClient(cfg)
	userService := &service.UserService{
		UsersRepo: users,
		Redis:     redisClient,
	}
	weChatService := &service.WeChatService{
		Config: cfg,
	}
	ossConfig := config.ProvideOssConfig(cfg)
	iOssService := service.NewOssService(ossConfig)
	auth := &handler.Auth{
		Config:        cfg,
		UserService:   userService,
		WeChatService: weChatService,
		OssService:    iOssService,
	}
	mapDao := dao.NewMapDao()
	mapService := &service.MapService{
		MapDao: mapDao,
	}
	handlerMap := &handler.Map{
		MapService: mapService,
		OssService: iOssService,
	}
	handlers := &server.Handlers{
		Auth: auth,
		Map:  handlerMap,
	}
	engine := server.NewGinEngine(handlers)
	appProvider := &server.AppProvider{
		Config: cfg,
		Engine: engine,
	}
	return appProvider
}
