// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Hyper/config"
	"Hyper/dao"
	"Hyper/dao/cache"
	"Hyper/handler"
	"Hyper/pkg/client"
	"Hyper/pkg/database"
	"Hyper/pkg/rocketmq"
	"Hyper/pkg/server"
	"Hyper/service"
)

// Injectors from wire.go:

func InitServer(cfg *config.Config) *server.AppProvider {
	db := database.NewDB(cfg)
	users := dao.NewUsers(db)
	redisClient := client.NewRedisClient(cfg)
	userService := &service.UserService{
		UsersRepo: users,
		Redis:     redisClient,
		DB:        db,
	}
	weChatService := &service.WeChatService{
		Config: cfg,
	}
	ossConfig := config.ProvideOssConfig(cfg)
	image := dao.NewImage(db)
	iOssService := service.NewOssService(ossConfig, image)
	userFollowDAO := dao.NewUserFollowDAO(db)
	userStatsDAO := dao.NewUserStatsDAO(db)
	rocketMQConfig := config.ProvideRocketMQConfig(cfg)
	producer := rocketmq.InitProducer(rocketMQConfig)
	followService := &service.FollowService{
		FollowDAO: userFollowDAO,
		StatsDAO:  userStatsDAO,
		UserDAO:   users,
		Producer:  producer,
		Redis:     redisClient,
	}
	noteLikeDAO := dao.NewNoteLikeDAO(db)
	noteStatsDAO := dao.NewNoteStatsDAO(db)
	noteDAO := dao.NewNoteDAO(db)
	likeService := &service.LikeService{
		LikeDAO:  noteLikeDAO,
		StatsDAO: noteStatsDAO,
		NoteDAO:  noteDAO,
		Redis:    redisClient,
	}
	noteCollectionDAO := dao.NewNoteCollectionDAO(db)
	collectService := &service.CollectService{
		CollectionDAO: noteCollectionDAO,
		StatsDAO:      noteStatsDAO,
		NoteDAO:       noteDAO,
		Redis:         redisClient,
	}
	auth := &handler.Auth{
		Config:         cfg,
		UserService:    userService,
		WeChatService:  weChatService,
		OssService:     iOssService,
		FollowService:  followService,
		LikeService:    likeService,
		CollectService: collectService,
	}
	mapDao := dao.NewMapDao()
	mapService := &service.MapService{
		MapDao: mapDao,
	}
	handlerMap := &handler.Map{
		MapService: mapService,
		OssService: iOssService,
		Redis:      redisClient,
	}
	messageDAO := dao.NewMessageDAO(db)
	messageService := &service.MessageService{
		MessageDao: messageDAO,
		MqProducer: producer,
		Redis:      redisClient,
		DB:         db,
	}
	unreadStorage := cache.NewUnreadStorage(redisClient)
	message := &handler.Message{
		MessageService: messageService,
		UnreadStorage:  unreadStorage,
		UserService:    userService,
		Config:         cfg,
	}
	comment := dao.NewComment(db)
	commentLike := dao.NewCommentLike(db)
	commentsService := &service.CommentsService{
		DB:             db,
		CommentDAO:     comment,
		CommentLikeDAO: commentLike,
		UserService:    userService,
		Redis:          redisClient,
	}
	topic := dao.NewTopic(db)
	topicService := &service.TopicService{
		Config:      cfg,
		DB:          db,
		TopicDAO:    topic,
		NoteDAO:     noteDAO,
		UserService: userService,
		LikeService: likeService,
		Redis:       redisClient,
	}
	noteService := &service.NoteService{
		NoteDAO:        noteDAO,
		CommentDAO:     comment,
		UserService:    userService,
		LikeService:    likeService,
		RedisClient:    redisClient,
		StatsDAO:       noteStatsDAO,
		FollowService:  followService,
		CollectService: collectService,
		CommentService: commentsService,
		TopicService:   topicService,
	}
	note := &handler.Note{
		OssService:     iOssService,
		NoteService:    noteService,
		LikeService:    likeService,
		CollectService: collectService,
		Config:         cfg,
	}
	follow := &handler.Follow{
		Config:        cfg,
		FollowService: followService,
		MqProducer:    producer,
	}
	serviceFollowService := service.FollowService{
		FollowDAO: userFollowDAO,
		StatsDAO:  userStatsDAO,
		UserDAO:   users,
		Producer:  producer,
		Redis:     redisClient,
	}
	serviceLikeService := service.LikeService{
		LikeDAO:  noteLikeDAO,
		StatsDAO: noteStatsDAO,
		NoteDAO:  noteDAO,
		Redis:    redisClient,
	}
	serviceCollectService := service.CollectService{
		CollectionDAO: noteCollectionDAO,
		StatsDAO:      noteStatsDAO,
		NoteDAO:       noteDAO,
		Redis:         redisClient,
	}
	user := &handler.User{
		Config:         cfg,
		UserService:    userService,
		OssService:     iOssService,
		FollowService:  serviceFollowService,
		LikeService:    serviceLikeService,
		CollectService: serviceCollectService,
	}
	messageStorage := cache.NewMessageStorage(redisClient)
	sessionDAO := dao.NewSessionDAO(db)
	sessionService := &service.SessionService{
		DB:             db,
		MessageStorage: messageStorage,
		UnreadStorage:  unreadStorage,
		UserService:    userService,
		SessionDAO:     sessionDAO,
	}
	session := &handler.Session{
		SessionService: sessionService,
		Config:         cfg,
	}
	groupService := &service.GroupService{
		DB: db,
	}
	groupHandler := &handler.GroupHandler{
		Config:       cfg,
		GroupService: groupService,
	}
	groupMemberService := &service.GroupMemberService{
		DB: db,
	}
	groupMemberHandler := &handler.GroupMemberHandler{
		Config:             cfg,
		GroupMemberService: groupMemberService,
	}
	commentsHandler := &handler.CommentsHandler{
		Config:          cfg,
		CommentsService: commentsService,
	}
	topicHandler := &handler.TopicHandler{
		Config:       cfg,
		TopicService: topicService,
	}
	handlers := &server.Handlers{
		Auth:            auth,
		Map:             handlerMap,
		Message:         message,
		Note:            note,
		Follow:          follow,
		User:            user,
		Session:         session,
		Group:           groupHandler,
		GroupMember:     groupMemberHandler,
		CommentsHandler: commentsHandler,
		TopicHandler:    topicHandler,
	}
	engine := server.NewGinEngine(handlers)
	appProvider := &server.AppProvider{
		Config: cfg,
		Engine: engine,
	}
	return appProvider
}
