// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Hyper/config"
	"Hyper/dao"
	"Hyper/dao/cache"
	"Hyper/handler"
	"Hyper/pkg/client"
	"Hyper/pkg/database"
	"Hyper/pkg/rocketmq"
	"Hyper/pkg/server"
	"Hyper/service"
)

// Injectors from wire.go:

func InitServer(cfg *config.Config) *server.AppProvider {
	db := database.NewDB(cfg)
	users := dao.NewUsers(db)
	redisClient := client.NewRedisClient(cfg)
	userService := &service.UserService{
		UsersRepo: users,
		Redis:     redisClient,
		DB:        db,
	}
	weChatService := &service.WeChatService{
		Config: cfg,
	}
	ossConfig := config.ProvideOssConfig(cfg)
	iOssService := service.NewOssService(ossConfig)
	userFollowDAO := dao.NewUserFollowDAO(db)
	userStatsDAO := dao.NewUserStatsDAO(db)
	followService := &service.FollowService{
		FollowDAO: userFollowDAO,
		StatsDAO:  userStatsDAO,
		UserDAO:   users,
	}
	noteLikeDAO := dao.NewNoteLikeDAO(db)
	noteStatsDAO := dao.NewNoteStatsDAO(db)
	noteDAO := dao.NewNoteDAO(db)
	likeService := &service.LikeService{
		LikeDAO:  noteLikeDAO,
		StatsDAO: noteStatsDAO,
		NoteDAO:  noteDAO,
	}
	noteCollectionDAO := dao.NewNoteCollectionDAO(db)
	collectService := &service.CollectService{
		CollectionDAO: noteCollectionDAO,
		StatsDAO:      noteStatsDAO,
		NoteDAO:       noteDAO,
	}
	auth := &handler.Auth{
		Config:         cfg,
		UserService:    userService,
		WeChatService:  weChatService,
		OssService:     iOssService,
		FollowService:  followService,
		LikeService:    likeService,
		CollectService: collectService,
	}
	mapDao := dao.NewMapDao()
	mapService := &service.MapService{
		MapDao: mapDao,
	}
	handlerMap := &handler.Map{
		MapService: mapService,
		OssService: iOssService,
		Redis:      redisClient,
	}
	messageDAO := dao.NewMessageDAO(db)
	producer := rocketmq.InitProducer()
	messageService := &service.MessageService{
		MessageDao: messageDAO,
		MqProducer: producer,
		Redis:      redisClient,
		DB:         db,
	}
	unreadStorage := cache.NewUnreadStorage(redisClient)
	message := &handler.Message{
		MessageService: messageService,
		UnreadStorage:  unreadStorage,
		UserService:    userService,
		Config:         cfg,
	}
	noteService := &service.NoteService{
		NoteDAO: noteDAO,
	}
	note := &handler.Note{
		OssService:     iOssService,
		NoteService:    noteService,
		LikeService:    likeService,
		CollectService: collectService,
		Config:         cfg,
	}
	follow := &handler.Follow{
		Config:        cfg,
		FollowService: followService,
	}
	user := &handler.User{
		Config:      cfg,
		UserService: userService,
		OssService:  iOssService,
	}
	messageStorage := cache.NewMessageStorage(redisClient)
	sessionService := &service.SessionService{
		DB:             db,
		MessageStorage: messageStorage,
		UnreadStorage:  unreadStorage,
		UserService:    userService,
	}
	session := &handler.Session{
		SessionService: sessionService,
		Config:         cfg,
	}
	handlers := &server.Handlers{
		Auth:    auth,
		Map:     handlerMap,
		Message: message,
		Note:    note,
		Follow:  follow,
		User:    user,
		Session: session,
	}
	engine := server.NewGinEngine(handlers)
	appProvider := &server.AppProvider{
		Config: cfg,
		Engine: engine,
	}
	return appProvider
}
