// Code generated by Kitex v0.15.4. DO NOT EDIT.

package pushservice

import (
	push "Hyper/rpc/kitex_gen/im/push"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PushToClient(ctx context.Context, req *push.PushRequest, callOptions ...callopt.Option) (r *push.PushResponse, err error)
	BatchPushToClient(ctx context.Context, req *push.BatchPushRequest, callOptions ...callopt.Option) (r *push.PushResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPushServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPushServiceClient struct {
	*kClient
}

func (p *kPushServiceClient) PushToClient(ctx context.Context, req *push.PushRequest, callOptions ...callopt.Option) (r *push.PushResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PushToClient(ctx, req)
}

func (p *kPushServiceClient) BatchPushToClient(ctx context.Context, req *push.BatchPushRequest, callOptions ...callopt.Option) (r *push.PushResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BatchPushToClient(ctx, req)
}
