// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Hyper/config"
	"Hyper/dao"
	"Hyper/dao/cache"
	"Hyper/pkg/client"
	"Hyper/pkg/database"
	"Hyper/pkg/rocketmq"
	socket2 "Hyper/pkg/socket"
	"Hyper/service"
	"Hyper/socket"
	"Hyper/socket/handler"
	"Hyper/socket/handler/event"
	"Hyper/socket/handler/event/chat"
	"Hyper/socket/process"
	"Hyper/socket/router"
)

// Injectors from wire.go:

func InitSocketServer(cfg *config.Config) *socket.AppProvider {
	redisClient := client.NewRedisClient(cfg)
	serverStorage := cache.NewSidStorage(redisClient)
	clientStorage := cache.NewClientStorage(redisClient, cfg, serverStorage)
	clientConnectService := &service.ClientConnectService{
		Storage: clientStorage,
	}
	db := database.NewDB(cfg)
	relation := cache.NewRelation(redisClient)
	groupMember := dao.NewGroupMember(db, relation)
	groupMemberService := &service.GroupMemberService{
		Db:              db,
		Redis:           redisClient,
		GroupMemberRepo: groupMember,
	}
	chatHandler := &chat.Handler{
		Redis: redisClient,
	}
	roomStorage := socket2.NewRoomStorage()
	chatEvent := &event.ChatEvent{
		Redis:           redisClient,
		GroupMemberRepo: groupMember,
		MemberService:   groupMemberService,
		Handler:         chatHandler,
		RoomStorage:     roomStorage,
	}
	chatChannel := &handler.ChatChannel{
		Storage: clientConnectService,
		Event:   chatEvent,
	}
	handlerHandler := &handler.Handler{
		Chat:        chatChannel,
		Config:      cfg,
		RoomStorage: roomStorage,
	}
	engine := router.NewRouter(cfg, handlerHandler)
	healthSubscribe := process.NewHealthSubscribe(serverStorage)
	rocketMQConfig := config.ProvideRocketMQConfig(cfg)
	pushConsumer := rocketmq.InitConsumer(rocketMQConfig)
	messageDAO := dao.NewMessageDAO(db)
	producer := rocketmq.InitProducer(rocketMQConfig)
	messageService := &service.MessageService{
		MessageDao: messageDAO,
		MqProducer: producer,
		Redis:      redisClient,
		DB:         db,
	}
	messageStorage := cache.NewMessageStorage(redisClient)
	unreadStorage := cache.NewUnreadStorage(redisClient)
	users := dao.NewUsers(db)
	userService := &service.UserService{
		UsersRepo: users,
		Redis:     redisClient,
		DB:        db,
	}
	sessionService := &service.SessionService{
		DB:             db,
		MessageStorage: messageStorage,
		UnreadStorage:  unreadStorage,
		UserService:    userService,
	}
	messageSubscribe := &process.MessageSubscribe{
		Redis:          redisClient,
		MqConsumer:     pushConsumer,
		DB:             db,
		MessageService: messageService,
		MessageStorage: messageStorage,
		SessionService: sessionService,
		UnreadStorage:  unreadStorage,
	}
	noticeSubscribe := &process.NoticeSubscribe{
		Redis:          redisClient,
		MqConsumer:     pushConsumer,
		ConnectService: clientConnectService,
	}
	subServers := &process.SubServers{
		HealthSubscribe:  healthSubscribe,
		MessageSubscribe: messageSubscribe,
		NoticeSubscribe:  noticeSubscribe,
	}
	server := process.NewServer(subServers, pushConsumer)
	appProvider := &socket.AppProvider{
		Config:    cfg,
		Engine:    engine,
		Coroutine: server,
		Handler:   handlerHandler,
	}
	return appProvider
}
