// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package push

import (
	"context"
	"fmt"
)

type PushRequest struct {
	Cid     int64  `thrift:"cid,1" frugal:"1,default,i64" json:"cid"`
	Uid     int32  `thrift:"uid,2" frugal:"2,default,i32" json:"uid"`
	Payload string `thrift:"payload,3" frugal:"3,default,string" json:"payload"`
	Event   string `thrift:"event,4" frugal:"4,default,string" json:"event"`
}

func NewPushRequest() *PushRequest {
	return &PushRequest{}
}

func (p *PushRequest) InitDefault() {
}

func (p *PushRequest) GetCid() (v int64) {
	return p.Cid
}

func (p *PushRequest) GetUid() (v int32) {
	return p.Uid
}

func (p *PushRequest) GetPayload() (v string) {
	return p.Payload
}

func (p *PushRequest) GetEvent() (v string) {
	return p.Event
}
func (p *PushRequest) SetCid(val int64) {
	p.Cid = val
}
func (p *PushRequest) SetUid(val int32) {
	p.Uid = val
}
func (p *PushRequest) SetPayload(val string) {
	p.Payload = val
}
func (p *PushRequest) SetEvent(val string) {
	p.Event = val
}

func (p *PushRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PushRequest(%+v)", *p)
}

var fieldIDToName_PushRequest = map[int16]string{
	1: "cid",
	2: "uid",
	3: "payload",
	4: "event",
}

type PushResponse struct {
	Success bool   `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Msg     string `thrift:"msg,2" frugal:"2,default,string" json:"msg"`
}

func NewPushResponse() *PushResponse {
	return &PushResponse{}
}

func (p *PushResponse) InitDefault() {
}

func (p *PushResponse) GetSuccess() (v bool) {
	return p.Success
}

func (p *PushResponse) GetMsg() (v string) {
	return p.Msg
}
func (p *PushResponse) SetSuccess(val bool) {
	p.Success = val
}
func (p *PushResponse) SetMsg(val string) {
	p.Msg = val
}

func (p *PushResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PushResponse(%+v)", *p)
}

var fieldIDToName_PushResponse = map[int16]string{
	1: "success",
	2: "msg",
}

type PushService interface {
	PushToClient(ctx context.Context, req *PushRequest) (r *PushResponse, err error)
}

type PushServicePushToClientArgs struct {
	Req *PushRequest `thrift:"req,1" frugal:"1,default,PushRequest" json:"req"`
}

func NewPushServicePushToClientArgs() *PushServicePushToClientArgs {
	return &PushServicePushToClientArgs{}
}

func (p *PushServicePushToClientArgs) InitDefault() {
}

var PushServicePushToClientArgs_Req_DEFAULT *PushRequest

func (p *PushServicePushToClientArgs) GetReq() (v *PushRequest) {
	if !p.IsSetReq() {
		return PushServicePushToClientArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PushServicePushToClientArgs) SetReq(val *PushRequest) {
	p.Req = val
}

func (p *PushServicePushToClientArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PushServicePushToClientArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PushServicePushToClientArgs(%+v)", *p)
}

var fieldIDToName_PushServicePushToClientArgs = map[int16]string{
	1: "req",
}

type PushServicePushToClientResult struct {
	Success *PushResponse `thrift:"success,0,optional" frugal:"0,optional,PushResponse" json:"success,omitempty"`
}

func NewPushServicePushToClientResult() *PushServicePushToClientResult {
	return &PushServicePushToClientResult{}
}

func (p *PushServicePushToClientResult) InitDefault() {
}

var PushServicePushToClientResult_Success_DEFAULT *PushResponse

func (p *PushServicePushToClientResult) GetSuccess() (v *PushResponse) {
	if !p.IsSetSuccess() {
		return PushServicePushToClientResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PushServicePushToClientResult) SetSuccess(x interface{}) {
	p.Success = x.(*PushResponse)
}

func (p *PushServicePushToClientResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PushServicePushToClientResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PushServicePushToClientResult(%+v)", *p)
}

var fieldIDToName_PushServicePushToClientResult = map[int16]string{
	0: "success",
}
